-- Toda tabela nasce com vínculo a empresa: costura para multi-cliente (SaaS) no futuro.

CREATE TABLE empresa (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL
);

CREATE TABLE plano_fluxo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa (id),
    nome       VARCHAR(120) NOT NULL,
    ano        INT NOT NULL
);

CREATE TABLE item_fluxo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id        BIGINT NOT NULL REFERENCES plano_fluxo (id) ON DELETE CASCADE,
    descricao       VARCHAR(200) NOT NULL,
    mecanismo       VARCHAR(30)  NOT NULL,
    mecanismo_outro VARCHAR(100),
    nota            VARCHAR(2000),
    ordem           INT NOT NULL DEFAULT 0
);

CREATE TABLE valor_mensal (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES item_fluxo (id) ON DELETE CASCADE,
    mes     INT NOT NULL CHECK (mes BETWEEN 1 AND 12),
    valor   NUMERIC(15, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_valor_item_mes UNIQUE (item_id, mes)
);

CREATE TABLE orcamento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id       BIGINT NOT NULL REFERENCES plano_fluxo (id) ON DELETE CASCADE,
    descricao      VARCHAR(200) NOT NULL,
    valor_unitario NUMERIC(15, 2) NOT NULL DEFAULT 0,
    quantidade     INT NOT NULL DEFAULT 1
);

INSERT INTO empresa (nome) VALUES ('Empresa Demo');
