-- Módulo de análise de crédito: clientes analisados, demonstrativos,
-- política de score (seed = política SulGesso mapeada da planilha) e análises.

CREATE TABLE cliente (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa (id),
    nome       VARCHAR(200) NOT NULL,
    cpf_cnpj   VARCHAR(20),
    tipo       VARCHAR(20) NOT NULL DEFAULT 'PRODUTOR',
    municipio  VARCHAR(120),
    uf         VARCHAR(2)
);

-- Contas granulares para alimentar tanto os indicadores quanto o modelo Fleuriet
-- (agregados AC/PC/AT são sempre derivados, nunca digitados — evita inconsistência).
CREATE TABLE demonstrativo (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id                    BIGINT NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    exercicio                     INT NOT NULL,
    receita_bruta                 NUMERIC(15, 2) NOT NULL DEFAULT 0,
    lucro_liquido                 NUMERIC(15, 2) NOT NULL DEFAULT 0,
    caixa_bancos                  NUMERIC(15, 2) NOT NULL DEFAULT 0,
    aplicacoes                    NUMERIC(15, 2) NOT NULL DEFAULT 0,
    contas_receber                NUMERIC(15, 2) NOT NULL DEFAULT 0,
    estoques                      NUMERIC(15, 2) NOT NULL DEFAULT 0,
    outros_ativos_circulantes     NUMERIC(15, 2) NOT NULL DEFAULT 0,
    realizavel_longo_prazo        NUMERIC(15, 2) NOT NULL DEFAULT 0,
    imobilizado                   NUMERIC(15, 2) NOT NULL DEFAULT 0,
    emprestimos_curto_prazo       NUMERIC(15, 2) NOT NULL DEFAULT 0,
    fornecedores                  NUMERIC(15, 2) NOT NULL DEFAULT 0,
    salarios_a_pagar              NUMERIC(15, 2) NOT NULL DEFAULT 0,
    outras_obrigacoes_circulantes NUMERIC(15, 2) NOT NULL DEFAULT 0,
    passivo_nao_circulante        NUMERIC(15, 2) NOT NULL DEFAULT 0,
    patrimonio_liquido            NUMERIC(15, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_demonstrativo_cliente_ano UNIQUE (cliente_id, exercicio)
);

CREATE TABLE politica_credito (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id           BIGINT NOT NULL REFERENCES empresa (id),
    versao               INT NOT NULL,
    nome                 VARCHAR(120) NOT NULL,
    inflacao_referencia  NUMERIC(6, 2) NOT NULL DEFAULT 4.62,
    vigente              BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE subcriterio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    politica_id BIGINT NOT NULL REFERENCES politica_credito (id) ON DELETE CASCADE,
    grupo       VARCHAR(60) NOT NULL,
    codigo      VARCHAR(10) NOT NULL,
    nome        VARCHAR(150) NOT NULL,
    peso        NUMERIC(6, 4) NOT NULL,
    automatico  BOOLEAN NOT NULL DEFAULT FALSE,
    ordem       INT NOT NULL
);

CREATE TABLE opcao_resposta (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcriterio_id BIGINT NOT NULL REFERENCES subcriterio (id) ON DELETE CASCADE,
    rotulo         VARCHAR(120) NOT NULL,
    nota           INT NOT NULL,
    ordem          INT NOT NULL
);

CREATE TABLE analise_credito (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id        BIGINT NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    politica_id       BIGINT NOT NULL REFERENCES politica_credito (id),
    status            VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
    observacoes       VARCHAR(4000),
    criada_em         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concluida_em      TIMESTAMP,
    -- Snapshot congelado na conclusão (análise concluída nunca é recalculada)
    score             NUMERIC(6, 2),
    rating            VARCHAR(3),
    percentual_limite NUMERIC(6, 4),
    base_limite       NUMERIC(15, 2),
    limite_calculado  NUMERIC(15, 2)
);

CREATE TABLE resposta_analise (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analise_id     BIGINT NOT NULL REFERENCES analise_credito (id) ON DELETE CASCADE,
    subcriterio_id BIGINT NOT NULL REFERENCES subcriterio (id),
    opcao_id       BIGINT NOT NULL REFERENCES opcao_resposta (id),
    justificativa  VARCHAR(2000),
    CONSTRAINT uq_resposta_analise_sub UNIQUE (analise_id, subcriterio_id)
);

-- ============================================================
-- SEED: política SulGesso v1 (pesos e opções mapeados da planilha PADRAO_PLANILHA1.1)
-- ============================================================

INSERT INTO politica_credito (id, empresa_id, versao, nome, inflacao_referencia, vigente)
VALUES (1, 1, 1, 'Política SulGesso v1', 4.62, TRUE);

INSERT INTO subcriterio (id, politica_id, grupo, codigo, nome, peso, automatico, ordem) VALUES
 (1,  1, 'Relacionamento Mercado', '1.1', 'Conceito Comercial',                     0.1000, FALSE, 1),
 (2,  1, 'Relacionamento Mercado', '1.2', 'Conceito Bancário',                      0.1500, FALSE, 2),
 (3,  1, 'Relacionamento Mercado', '1.3', 'Restrições SERASA e/ou Cartórios',       0.3000, FALSE, 3),
 (4,  1, 'Histórico Comercial',    '2.1', 'Histórico de Crédito',                   0.0500, FALSE, 4),
 (5,  1, 'Histórico Comercial',    '2.2', 'Tempo do Cliente',                       0.0500, FALSE, 5),
 (6,  1, 'Histórico Comercial',    '2.3', 'Tempo de Mercado',                       0.0500, FALSE, 6),
 (7,  1, 'Análise de Balanço',     '3.1', 'Evolução das Vendas',                    0.0500, TRUE,  7),
 (8,  1, 'Análise de Balanço',     '3.2', 'Rentabilidade do PL (ROE)',              0.0500, TRUE,  8),
 (9,  1, 'Análise de Balanço',     '3.3', 'Grau de Endividamento sobre Ativo Total',0.0500, TRUE,  9),
 (10, 1, 'Análise de Balanço',     '3.4', 'Grau de Liquidez Seca',                  0.0500, TRUE, 10),
 (11, 1, 'Risco Operacional',      '4.1', 'Principal Fornecedor (Bandeira Venda)',  0.0250, FALSE, 11),
 (12, 1, 'Risco Operacional',      '4.2', 'Cliente Possui ERP / Sistema Cobrança',  0.0250, FALSE, 12),
 (13, 1, 'Risco Operacional',      '4.3', 'Número de Unidades de Negócio',          0.0250, FALSE, 13),
 (14, 1, 'Risco Operacional',      '4.4', 'Risco Produtivo e Climático da Região',  0.0250, FALSE, 14);

INSERT INTO opcao_resposta (subcriterio_id, rotulo, nota, ordem) VALUES
 (1, 'Excelente', 100, 1), (1, 'Bom', 70, 2), (1, 'Regular', 30, 3), (1, 'Sem informações', 0, 4),
 (2, 'Boas referências', 100, 1), (2, 'Referências c/ restrições', 20, 2), (2, 'Sem informações', 0, 3),
 (3, 'Sem restrições', 100, 1), (3, 'Com restrições não relevantes', 50, 2), (3, 'Com restrições', 0, 3),
 (4, 'Pontual', 100, 1), (4, 'Atraso entre 1 e 14 dias', 80, 2), (4, 'Atraso entre 15 e 30 dias', 60, 3),
 (4, 'Novo', 50, 4), (4, 'Atraso entre 31 e 60 dias', 40, 5), (4, 'Atraso entre 61 e 90 dias', 20, 6),
 (4, 'Atraso acima de 90 dias', 0, 7),
 (5, 'Acima de 5 anos', 100, 1), (5, 'De 3 a 5 anos', 80, 2), (5, 'De 1 a 2 anos', 50, 3), (5, 'Menos de 1 ano', 0, 4),
 (6, 'Acima de 10 anos', 100, 1), (6, 'De 6 a 10 anos', 80, 2), (6, 'De 4 a 5 anos', 50, 3), (6, 'De 0 a 3 anos', 0, 4),
 (7, 'Crescimento (acima da inflação)', 100, 1), (7, 'Estabilidade (positivo até a inflação)', 50, 2), (7, 'Declínio', 0, 3),
 (8, 'Elevada (acima de 15%)', 100, 1), (8, 'Regular (entre 10% e 14%)', 50, 2), (8, 'Baixa', 0, 3),
 (9, 'Baixa (50% para baixo)', 100, 1), (9, 'Regular (entre 51% e 79%)', 50, 2), (9, 'Elevada (acima de 80%)', 0, 3),
 (10, 'Elevada (acima de 1,0)', 100, 1), (10, 'Regular (abaixo de 1,0)', 0, 2),
 (11, '1º Nível', 100, 1), (11, '2º Nível', 50, 2), (11, 'Não possui', 20, 3),
 (12, 'Sim', 100, 1), (12, 'Não', 0, 2),
 (13, 'Mais de 12', 100, 1), (13, 'De 7 a 12', 70, 2), (13, 'De 4 a 6', 50, 3), (13, 'De 1 a 3', 10, 4),
 (14, 'Muito Baixo', 100, 1), (14, 'Baixo', 75, 2), (14, 'Médio', 50, 3), (14, 'Alto', 25, 4), (14, 'Muito Alto', 0, 5);
