-- Usuários (login por e-mail/senha), campos completos de cliente e UF no plano de fluxo.

CREATE TABLE usuario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa (id),
    nome       VARCHAR(120) NOT NULL,
    email      VARCHAR(180) NOT NULL,
    senha_hash VARCHAR(100) NOT NULL,
    ativo      BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

ALTER TABLE cliente ADD COLUMN telefone VARCHAR(30);
ALTER TABLE cliente ADD COLUMN email VARCHAR(180);
ALTER TABLE cliente ADD COLUMN endereco VARCHAR(300);

ALTER TABLE plano_fluxo ADD COLUMN uf VARCHAR(2);
