-- Vínculo plano→cliente, lançamentos diários de caixa e movimentos da carteira.

ALTER TABLE plano_fluxo ADD COLUMN cliente_id BIGINT REFERENCES cliente (id);

-- Extrato Bancário (realizado) + Contas Receber e Pagar (previsto) unificados:
-- mesma estrutura de lançamento, diferenciados por status. Saldo corrente é derivado.
CREATE TABLE lancamento_caixa (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id    BIGINT NOT NULL REFERENCES empresa (id),
    cliente_id    BIGINT REFERENCES cliente (id),
    data          DATE NOT NULL,
    classificacao VARCHAR(120),
    historico     VARCHAR(300),
    entrada       NUMERIC(15, 2) NOT NULL DEFAULT 0,
    saida         NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status        VARCHAR(20) NOT NULL DEFAULT 'REALIZADO'
);

-- Carteira: cada movimento aumenta (FATURAMENTO) ou reduz (PAGAMENTO) o saldo em aberto.
CREATE TABLE movimento_carteira (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    data       DATE NOT NULL,
    tipo       VARCHAR(20) NOT NULL,
    valor      NUMERIC(15, 2) NOT NULL DEFAULT 0,
    descricao  VARCHAR(300)
);
