-- Parâmetros da política (instrumento/fonte/validação/descrição da aba "Parâmetros")
-- e relato de campo estruturado (aba "Relato de Campo" — um por cliente, upsert).

ALTER TABLE subcriterio ADD COLUMN instrumento VARCHAR(60);
ALTER TABLE subcriterio ADD COLUMN fonte VARCHAR(60);
ALTER TABLE subcriterio ADD COLUMN validacao VARCHAR(60);
ALTER TABLE subcriterio ADD COLUMN descricao VARCHAR(200);

-- Dados da aba "Parâmetros" + anotações da aba "Política Crédito" (política v1)
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Relato comercial baseado em informações colhidas no campo' WHERE politica_id = 1 AND codigo = '1.1';
UPDATE subcriterio SET instrumento = 'Documento bancário',     fonte = 'RTVs',       validacao = 'Financeiro', descricao = 'Referência via carta bancária' WHERE politica_id = 1 AND codigo = '1.2';
UPDATE subcriterio SET instrumento = 'Consulta Serasa',        fonte = 'Financeiro', validacao = 'Financeiro', descricao = 'Baseado na pesquisa SERASA' WHERE politica_id = 1 AND codigo = '1.3';
UPDATE subcriterio SET instrumento = 'Consulta Base Sistema',  fonte = 'Financeiro', validacao = 'Financeiro', descricao = 'Baseado no histórico do cliente conosco' WHERE politica_id = 1 AND codigo = '2.1';
UPDATE subcriterio SET instrumento = 'Consulta Base Sistema',  fonte = 'Comercial',  validacao = 'Financeiro', descricao = 'Baseado no histórico do cliente conosco' WHERE politica_id = 1 AND codigo = '2.2';
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Baseado em relato da equipe comercial e/ou data de abertura do contrato social' WHERE politica_id = 1 AND codigo = '2.3';
UPDATE subcriterio SET instrumento = 'Demonstrações Contábeis', fonte = 'RTVs',      validacao = 'Financeiro', descricao = 'Baseado na análise dos Balanços apresentados' WHERE politica_id = 1 AND codigo = '3.1';
UPDATE subcriterio SET instrumento = 'Demonstrações Contábeis', fonte = 'RTVs',      validacao = 'Financeiro', descricao = 'Baseado na análise dos Balanços apresentados' WHERE politica_id = 1 AND codigo = '3.2';
UPDATE subcriterio SET instrumento = 'Demonstrações Contábeis', fonte = 'RTVs',      validacao = 'Financeiro', descricao = 'Baseado na análise dos Balanços apresentados' WHERE politica_id = 1 AND codigo = '3.3';
UPDATE subcriterio SET instrumento = 'Demonstrações Contábeis', fonte = 'RTVs',      validacao = 'Financeiro', descricao = 'Baseado na análise dos Balanços apresentados' WHERE politica_id = 1 AND codigo = '3.4';
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Baseado em relato comercial' WHERE politica_id = 1 AND codigo = '4.1';
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Baseado em relato comercial' WHERE politica_id = 1 AND codigo = '4.2';
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Baseado em relato comercial' WHERE politica_id = 1 AND codigo = '4.3';
UPDATE subcriterio SET instrumento = 'Relato de Campo',        fonte = 'RTVs',       validacao = 'Comercial',  descricao = 'Baseado em relato comercial' WHERE politica_id = 1 AND codigo = '4.4';

-- Relato de campo estruturado: um por cliente (upsert), alimenta os subcritérios 1.1, 2.3 e 4.x
CREATE TABLE relato_campo (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id                        BIGINT NOT NULL UNIQUE REFERENCES cliente (id) ON DELETE CASCADE,
    conceito_comercial                VARCHAR(40),
    conceito_comercial_justificativa  VARCHAR(2000),
    tempo_mercado                     VARCHAR(40),
    tempo_mercado_justificativa       VARCHAR(2000),
    bandeira                          VARCHAR(40),
    bandeira_justificativa            VARCHAR(2000),
    possui_erp                        BOOLEAN,
    possui_cobranca                   BOOLEAN,
    unidades_negocio                  VARCHAR(40),
    unidades_negocio_justificativa    VARCHAR(2000),
    risco_climatico                   VARCHAR(40),
    risco_climatico_justificativa     VARCHAR(2000),
    observacoes                       VARCHAR(4000),
    atualizado_em                     TIMESTAMP
);
