-- V8: Relato de campo múltiplo, perfil de usuário, campos extras no demonstrativo
--
-- Idempotente: funciona em DB limpo (H2 testes) e no estado parcial do Neon
-- (onde cliente_id já foi dropado e cliente_id_new existe com dados).
-- FlywayRepairConfig.repair() limpa migração com falha antes de re-executar.

-- 1) Relato de campo: remover UNIQUE de cliente_id (permitir múltiplos por cliente)
ALTER TABLE relato_campo ADD COLUMN IF NOT EXISTS cliente_id_new BIGINT;
ALTER TABLE relato_campo DROP COLUMN IF EXISTS cliente_id;
ALTER TABLE relato_campo DROP COLUMN IF EXISTS cliente_id_tmp;
ALTER TABLE relato_campo RENAME COLUMN cliente_id_new TO cliente_id;
ALTER TABLE relato_campo ALTER COLUMN cliente_id SET NOT NULL;
ALTER TABLE relato_campo ADD FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE;

ALTER TABLE relato_campo ADD COLUMN IF NOT EXISTS titulo VARCHAR(120);

-- 2) Perfil de usuário
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS perfil VARCHAR(20) DEFAULT 'ADMINISTRADOR' NOT NULL;

-- 3) Campos extras dinâmicos no demonstrativo (Ativo/Passivo customizáveis)
CREATE TABLE IF NOT EXISTS demonstrativo_campo_extra (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demonstrativo_id BIGINT NOT NULL REFERENCES demonstrativo (id) ON DELETE CASCADE,
    grupo            VARCHAR(60)    NOT NULL,
    nome             VARCHAR(120)   NOT NULL,
    valor            DECIMAL(19,2)  NOT NULL DEFAULT 0
);
