-- V8: Relato de campo múltiplo, perfil de usuário, campos extras no demonstrativo

-- 1) Relato de campo: permitir múltiplos por cliente
--    Recria a coluna sem UNIQUE (H2 não permite DROP inline unique facilmente).
--    Estratégia portável: cria coluna nova, copia, dropa antiga, renomeia.
ALTER TABLE relato_campo ADD COLUMN cliente_id_new BIGINT;
UPDATE relato_campo SET cliente_id_new = cliente_id;
ALTER TABLE relato_campo DROP COLUMN cliente_id;
ALTER TABLE relato_campo ALTER COLUMN cliente_id_new RENAME TO cliente_id;
ALTER TABLE relato_campo ALTER COLUMN cliente_id SET NOT NULL;
ALTER TABLE relato_campo ADD FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE;
ALTER TABLE relato_campo ADD COLUMN IF NOT EXISTS titulo VARCHAR(120);

-- 2) Perfil de usuário
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS perfil VARCHAR(20) DEFAULT 'ADMINISTRADOR' NOT NULL;

-- 3) Campos extras dinâmicos no demonstrativo (Ativo/Passivo customizáveis)
CREATE TABLE IF NOT EXISTS demonstrativo_campo_extra (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demonstrativo_id BIGINT NOT NULL REFERENCES demonstrativo (id) ON DELETE CASCADE,
    grupo            VARCHAR(60)    NOT NULL,
    nome             VARCHAR(120)   NOT NULL,
    valor            DECIMAL(19,2)  NOT NULL DEFAULT 0
);
