-- V8: Relato de campo múltiplo, perfil de usuário, campos extras no demonstrativo
--
-- Idempotente: funciona em DB limpo (H2 testes) e no Neon (onde a V8 anterior
-- falhou e PostgreSQL fez rollback transacional — estado é pré-V8).
-- FlywayRepairConfig.repair() limpa a entrada FAILED antes de re-executar.

-- 1) Relato de campo: remover UNIQUE de cliente_id (permitir múltiplos por cliente)
ALTER TABLE relato_campo ADD COLUMN IF NOT EXISTS cliente_id_new BIGINT;
UPDATE relato_campo SET cliente_id_new = cliente_id WHERE cliente_id_new IS NULL;
ALTER TABLE relato_campo DROP COLUMN IF EXISTS cliente_id;
ALTER TABLE relato_campo DROP COLUMN IF EXISTS cliente_id_tmp;
ALTER TABLE relato_campo RENAME COLUMN cliente_id_new TO cliente_id;
DELETE FROM relato_campo WHERE cliente_id IS NULL;
ALTER TABLE relato_campo ALTER COLUMN cliente_id SET NOT NULL;
ALTER TABLE relato_campo ADD FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE;

ALTER TABLE relato_campo ADD COLUMN IF NOT EXISTS titulo VARCHAR(120);

-- 2) Perfil de usuário
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS perfil VARCHAR(20) DEFAULT 'ADMINISTRADOR' NOT NULL;

-- 3) Campos extras dinâmicos no demonstrativo (Ativo/Passivo customizáveis)
CREATE TABLE IF NOT EXISTS demonstrativo_campo_extra (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demonstrativo_id BIGINT NOT NULL REFERENCES demonstrativo (id) ON DELETE CASCADE,
    grupo            VARCHAR(60)    NOT NULL,
    nome             VARCHAR(120)   NOT NULL,
    valor            DECIMAL(19,2)  NOT NULL DEFAULT 0
);
