-- Prazo de crédito na carteira (por cliente)
ALTER TABLE cliente ADD COLUMN prazo_credito DATE;

-- Peso atribuído na Política de Crédito (persistido por cliente)
CREATE TABLE peso_atribuido (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa(id),
    cliente_id BIGINT NOT NULL REFERENCES cliente(id),
    opcao_id  BIGINT NOT NULL REFERENCES opcao_resposta(id),
    valor     INT    NOT NULL DEFAULT 0,
    UNIQUE (cliente_id, opcao_id)
);
